/**
 * 内置技能：给 aireader 写插件（P3.4）。
 *
 * 为什么把这份指南做成**技能**而不是塞进 system 提示：
 *   1. 它是按需的 —— 不写插件的用户不该为它付每一轮的 token（system 是每轮都发的）；
 *   2. 它是**做法**（procedure），正是技能的本职（内部设计笔记）；
 *   3. DSH 也是这么做的：cordis 那套的写法在 dsh-tool-cordis 的 SKILL.md 里，不在 system 里。
 *
 * system 提示里只留一段 4 行的分片（ai/prompt.ts 的 PLUGIN_SHARD）指到这里。
 */

export const WRITING_PLUGINS_SKILL = {
  name: "writing-plugins",
  description:
    "给鲸鲸写一个插件：加一块界面（显示剩余页数、进度、批注统计…）或加一个工具/服务。用户说「加一块界面」「让它显示…」「做个工具」「你能扩展自己吗」时使用。",
  whenToUse: "用户要求改阅读器本身的界面或能力，而不是问书里的内容时",
  body: [
    "# 给鲸鲸写插件",
    "",
    "鲸鲸的界面与工具都是插件挂上去的，你也能写。**四步，别跳**：",
    "",
    "1. **plugin_inspect** 查现场。至少查两次：",
    "   - `query=slots` —— 有哪些槽位、**接线了没有**（`wired: false` 的挂上去也不会显示）；",
    "   - `query=api` 与 `query=ui` —— ctx 能调什么、各需要哪个能力、界面能用哪些标签与属性。",
    "   **不要凭记忆猜槽位名与 API**，它们以 inspect 的结果为准。",
    "2. **plugin_define** 定义包（只定义，不运行、不授权）。",
    "3. **plugin_run** 运行。看回执的 `state`：",
    "   - `ACTIVE` —— 成了，`contributions` 就是它挂上的东西；",
    "   - `PENDING_PERMISSION` —— 在等用户授权（用户在右侧「插件」面板点授权后会**自动**挂起来）；",
    "   - `FAILED` —— 启动就炸了，去第 4 步。",
    "4. **plugin_diagnose** 看它为什么炸：版本指针、它有哪些包、**出错那一版的源码**、界面渲染失败记录。",
    "",
    "## 包长什么样",
    "",
    "一个包 = manifest + **宿主半**（`main`）+ 可选的 **UI 半**（`ui`）。",
    "manifest 由 `plugin_define` 的参数自动生成，你不用手写。两半**至少有一半**（纯界面插件把 main 传空串）。",
    "",
    "- 宿主半：函数体或 IIFE，必须交出 `function apply(ctx, config) { ... }`（或 `module.exports.apply`）。",
    "- UI 半：同样交出 `apply`，里面用 `ctx.slots.register(...)` 挂界面。",
    "",
    "**包是不可变的**：改了代码必须换版本号（不给 `version` 会自动 +1）。失败的那一版**不会被覆盖、也不会自动回滚** ——",
    "修 = `plugin_define` 追加新版本再 `plugin_run`；回滚 = 把旧的 `packageId` 传给 `plugin_run` 再跑一次。",
    "",
    "## ctx 能做什么（用到什么就声明什么能力）",
    "",
    "| 调用 | 需要的能力 | 说明 |",
    "|---|---|---|",
    "| `ctx.log(...)` | `log.write` | 写日志 |",
    "| `ctx.reader.progress()` | `reader.read` | **同步**。`{ fraction, chapter, location, sectionIndex, sectionTotal, sectionFraction, sectionStartFraction, sectionEndFraction, locations:{current,total} }` |",
    "| `ctx.reader.chapters()` | `reader.read` | 同步。章节索引；**没装载全书上下文时是空数组**，别依赖它 |",
    "| `ctx.reader.chapter(n, offset, maxChars)` | `reader.read` | 同步。第 n 章正文切片 |",
    "| `ctx.reader.selection()` | `reader.read` | 同步。当前选区 |",
    "| `await ctx.reader.search(q, limit)` | `reader.read` | 全文检索 |",
    "| `await ctx.reader.annotations()` | `reader.read` | 本书批注 |",
    "| `await ctx.reader.activity()` | `reader.read` | **阅读活动**（宿主已采集）：`{ today, todaySeconds, todayTurns, days:[{day,seconds,turns}], totalSeconds, activeDays, streak, longestStreak, bestDay }`。做热力图 / 阅读目标 / 连续天数用它 |",
    "| `await ctx.reader.addAnnotation({kind,cfi,text,note})` | `reader.annotate` | 写批注（会进用户的批注库，**先问过用户**） |",
    "| `await ctx.reader.gotoChapter/gotoCfi/gotoFraction` | `reader.navigate` | 改阅读位置 |",
    "| `await ctx.storage.get/set/remove/keys` | `storage.plugin` | 插件自己的存储（按插件隔离） |",
    "| `await ctx.net.fetch(url, {method?, headers?, body?})` | `net.fetch` | **宿主代发** HTTP。只能访问 manifest 里 `network.origins` 声明过、且用户授权了的域名。返回 `{ ok, status, url, contentType, text, truncated, note?, redirects }` |",
    "| （与 net.fetch 一起声明） | `ai.credentials` | 对你**已配置的 AI 服务**发 GET/HEAD 时，宿主自动带上 `Authorization`（Key 不进沙箱、不用用户再填；POST 会被拒） |",
    "| `ctx.tools.register(def, execute)` | （`def.capabilities` 必填） | 注册一个工具给 AI 用 |",
    "| `ctx.effect(fn)` | — | 注册清理；回调必须**同步** |",
    "| `ctx.provide('plugin.名字', 纯数据)` | — | 只放**数据**（函数过不了边界）。两半在**同一个 realm**：要共享可变状态就直接挂 `globalThis.__我的状态 = {...}`，两半都能读写 |",
    "| `ctx.slots.register(opts, render)` | `ui.slot` | 挂一块界面（见下） |",
    "| `ctx.slots.refresh()` | `ui.slot` | 让这块界面重渲染 |",
    "| `ctx.theme.overrideTokens({'--air-accent': '#c00'})` | `ui.theme` | 覆盖主题颜色。可覆盖 `--air-bg/panel/text/sub/border/hover/accent/cover-from/cover-to`，以及**正文三色** `--air-book-bg`（阅读背景）/`--air-book-text`/`--air-book-link`。值只能是颜色这类单值 |",
    "| `ctx.styles.insert(css, { scope })` | `ui.styles` | 插一段 CSS：`scope:'app'` 改外壳、`scope:'book'` 改**正文**（排版 / 页边 / 阅读背景）。插件卸载时自动撤；`ctx.styles.clear()` 主动撤掉自己插的 |",
    "| `ctx.timeout(fn, ms)` / `ctx.interval(fn, ms)` / `ctx.clear(h)` | — | 宿主定时器（沙箱里**没有** `setTimeout`）。卸载时宿主统一清理；interval 最小 100ms |",
    "| `ctx.env()` / `ctx.crypto.randomUUID()` / `ctx.text.*` | — | 宿主给出的事实与小工具：平台/触摸/视口/主题、随机 id、文件名与截断 |",
    "| `ctx.get('plugin.名字')` / `ctx.services()` | manifest 的 `inject` | 读**别的插件**提供的服务（纯数据）。先声明依赖才读得到；只认 `plugin.` 前缀 |",
    "",
    "没列的调用不存在：`ctx.on`（事件面）还没接，`llm.chat` / `fs.*` 还没有门面。",
    "",
    "### 网络（`net.fetch`）怎么用对",
    "",
    "1. **先声明域名**：`plugin_define` 里同时给 `capabilities: ['net.fetch']` 与 `network: { origins: ['api.deepseek.com'] }`",
    "   —— 少了域名会被拒（授权面板给用户看的就是这份清单：他授权的是「这几个域名」，不是「整个互联网」）。",
    "2. **密钥怎么来，分两种情况**：",
    "   - **就是你配置的那家 AI 服务**（查 DeepSeek 余额、查用量…）：再声明一个 `ai.credentials`，",
    "     宿主会对**该域名上的 GET/HEAD** 自动带上 `Authorization` —— **不用让用户再填一次 Key，Key 也不会进你的沙箱**。",
    "     限制：只 GET/HEAD（POST 会被拒，宿主不替插件花钱）、只对你配置的那个域名、用户换服务商后要重新授权。",
    "   - **别的服务**（GitHub token、某个第三方 API）：写进 `config`（JSON Schema），用户在「设置 → 插件」里填。",
    "   **绝对不要把 Key / Token 硬编码在代码里**（插件代码是可读、会进日志、会被导出的）。",
    "3. **拿到的只有文本**：返回 `text`（15 秒超时、512KB 上限、非文本类型不回传正文）；重定向最多 3 跳，",
    "   每一跳都要落在已授权域名里；不带 cookie（宿主代发，插件拿不到用户的登录态）。",
    "4. 只用 GET/POST/HEAD；要发 JSON 就自己 `JSON.stringify` 放进 body，并设 `headers: { 'content-type': 'application/json' }`。",
    "5. **config 里别把「用户还没填的字段」写成必填**（`required`）：必填没填 = 配置不合法 = **插件根本不挂载**，",
    "   于是用户连你的界面都看不到、也就看不到「去设置里填 Key」那句提示（实测踩到）。给默认值或设为可选，界面上再提示。",
    "6. 定时刷新用 `ctx.interval(fn, ms)`（宿主定时器，卸载时自动清；沙箱里没有 `setTimeout`，最小 100ms），拿到新数据后调 `ctx.slots.refresh()`。",
    "   「阅读时长」这类**事实**由宿主采集好了，用 `ctx.reader.activity()` 读，不要自己算。",
    "",
    "## 外观：颜色、阅读背景、排版",
    "",
    "用户说「背景太亮」「字号太小」「换个配色」时，按**代价从低到高**选：",
    "",
    "1. **只改颜色** → `ctx.theme.overrideTokens({ '--air-book-bg': '#f6f0e2', '--air-book-text': '#3b3226' })`（能力 `ui.theme`）。",
    "   `--air-*` 管应用外壳，`--air-book-bg / --air-book-text / --air-book-link` 管**正文（阅读背景）**。",
    "2. **改排版 / 页边 / 正文细节** → `ctx.styles.insert('body { line-height: 2 } p { text-indent: 0 }', { scope: 'book' })`（能力 `ui.styles`）。",
    "   正文里也能用 `var(--air-bg)` / `var(--air-book-bg)` 这些变量。",
    "3. **自己那块界面的样子 / 产品没提供的样式** → 同一个函数，`{ scope: 'app' }`（默认）。给自己挂的节点一个 `className`，再用 CSS 选中它。",
    "",
    "三条实测踩过的坑：",
    "",
    "- **正文在书自己的 iframe 里，是另一个 document**：外壳的 CSS 与 CSS 变量一个字节都进不去 ——",
    "  这就是「插件改了颜色没反应」的根因，必须走上面第 1 / 2 条（别在 app 作用域里写 `body` 指望改到正文）；",
    "- 样式里**不能** `@import`、也不能写远程 `url(...)`（会绕开 `net.fetch` 的域名授权，宿主直接拒）。要图标/字体请先 `ctx.net.fetch` 取回再内联，或用 data: URI；",
    "- 单插件 ≤16 张表、合计 ≤64KB；只能撤自己插的（`ctx.styles.clear()`）。",
    "",
    "## 依赖别的插件（前置服务 / inject）",
    "",
    "- **提供方**：`ctx.provide('plugin.stats', 纯数据)`（名字必须以 `plugin.` 开头；函数过不了沙箱边界）。",
    "- **使用方**：manifest 里写 `inject: ['plugin.stats']`，代码里 `ctx.get('plugin.stats')`；`ctx.services()` 列出当前有哪些可依赖。",
    "- **依赖没到不是错误**：容器会让你的插件先 park（状态 `PENDING`，不是失败），提供方挂上后自动继续；",
    "  提供方卸载时你也会被重新判定。所以别写「没装就自己造一份」这种兜底 —— 那会让用户看到两份不一致的数据。",
    "- 只认 `plugin.` 前缀：`reader` / `db` / `theme` 这些宿主能力走对应的 `ctx.*` 门面（那里才有能力门禁）。",
    "",
    "## UI 半：交出来的是**声明式界面**，不是 React",
    "",
    "跨沙箱传不了 React 元素，所以 `render` 返回一棵纯数据的**虚拟节点树**：",
    "",
    "    { type: '标签名', props: { ... }, children: [节点 | 字符串] }",
    "",
    "四条硬规则（违反了会被宿主拒绝，并且**这一格界面会被摘掉**）：",
    "",
    "0. **`ctx.slots.register` 的 opts 里，list / keyed 槽位必须给 `id`**（`id` 就是「格子」的标识：同一个 id 再注册是**替换**，不给会被拒）。例：`{ slot: 'library.view.top', id: 'balance', label: '余额' }`。",
    "1. **标签与属性必须在白名单里**（`plugin_inspect` 的 `query=ui` 给出全部）。不是完整 HTML：`script` / `iframe` / `dangerouslySetInnerHTML` 都没有。",
    "2. **render 必须同步返回**（不能是 `async`）：渲染期不能等 IO。要异步取数据就先取好存进插件自己的变量，再调 `ctx.slots.refresh()`。",
    "3. **事件的值必须是 `ui.handler(fn)` 返回的令牌**（JSON 里放不下函数）：",
    "",
    "       props: { onClick: ui.handler(function () { count = count + 1; ctx.slots.refresh(); }) }",
    "",
    "   令牌**每次渲染重建**：它只对最近一次渲染出来的那棵树有效。处理器跑完宿主会自动重渲染一次。",
    "4. 有深度（12 层）与节点数（**600**）上限：一年热力图那种 371 个格子画得下，但别无限铺列表。",
    "",
    "## 完整示例：在阅读区尾部显示「本章还剩多少页」",
    "",
    "```json",
    "{",
    "  \"pluginId\": \"ai.chapter-left-pages\",",
    "  \"name\": \"本章剩余页数\",",
    "  \"purpose\": \"在阅读区尾部显示当前章节还剩多少页、这一章共多少页。\",",
    "  \"capabilities\": [\"reader.read\", \"ui.slot\"],",
    "  \"main\": \"\",",
    "  \"ui\": \"function apply(ctx) { ... }\"",
    "}",
    "```",
    "",
    "`main` 留空（这个插件只有 UI 半）；`ui` 的完整内容：",
    "",
    "    function apply(ctx) {",
    "      ctx.slots.register(",
    "        { slot: 'reader.view.tail', id: 'left-pages', order: 5, label: '本章剩余页数' },",
    "        function (props, ui) {",
    "          var p = ctx.reader.progress() || {};",
    "          var start = p.sectionStartFraction === undefined ? 0 : p.sectionStartFraction;",
    "          var end = p.sectionEndFraction === undefined ? 1 : p.sectionEndFraction;",
    "          var span = Math.max(0.000001, end - start);       // 这一章占全书多少",
    "          var inChapter = p.sectionFraction === undefined ? 0 : p.sectionFraction;",
    "          var totalLoc = (p.locations && p.locations.total) || 100;",
    "          var pages = Math.max(1, Math.round(span * totalLoc));   // 把全书位置数按章的比例切一刀",
    "          var left = Math.max(0, Math.round(pages * (1 - inChapter)));",
    "          return {",
    "            type: 'div',",
    "            props: { className: 'air-slot-tail' },",
    "            children: [",
    "              { type: 'span', props: {}, children: ['本章约剩 ' + left + ' 页 / 共 ' + pages + ' 页'] },",
    "            ],",
    "          };",
    "        },",
    "      );",
    "    }",
    "",
    "注意 `slot` 用的是 inspect 里查到的**准确名字**；`props.className` 用的是宿主已有的样式类（`air-slot-tail`），这样它看起来与内置的那条一致。",
    "",
    "## 加一个工具（宿主半）",
    "",
    "    function apply(ctx) {",
    "      ctx.tools.register({",
    "        name: 'reading_left_pages',",
    "        description: '算出当前章节还剩多少页',",
    "        parameters: { type: 'object', properties: {} },",
    "        capabilities: ['reader.read'],",
    "      }, async function () {",
    "        var p = ctx.reader.progress();",
    "        return { chapter: p.chapter, fraction: p.fraction };",
    "      });",
    "    }",
    "",
    "工具名只能用小写字母/数字/下划线；`capabilities` 必填，且必须是 manifest 里声明过的能力的子集。",
    "**工具名是全局唯一的**：不要注册一个别的插件已经用过的名字，也别在同一个包里注册两次同名工具 ——",
    "重复会让整个包 `apply 失败`（实测：模型写「余额」插件时与旧的余额插件撞名，折腾了三轮）。",
    "",
    "**两半怎么共享状态**：`main` 与 `ui` 跑在**同一个 realm**，最省事的做法是",
    "`globalThis.__myState = { ... }`（main 里写、ui 的 render 里读）。**不要**试图用 `ctx.provide` 传函数 ——",
    "它只接受纯数据（传函数会明确报「只能给纯数据」）。",
    "",
    "## 界面挂在哪（槽位）",
    "",
    "以 `plugin_inspect(query=slots)` 的结果为准，常用的几个：",
    "",
    "| 槽位 | 显示在哪 |",
    "|---|---|",
    "| `library.view.top` | **书库页（主页）书架上方** —— 「在主页加一块东西」（统计、热力图、推荐）用它 |",
    "| `reader.view.tail` | 阅读区底部的一条（当前这本书的状态） |",
    "| `sidebar.footer.action` | 侧栏底部（很窄，只放得下一行小字） |",
    "| `settings.section` | 「设置与插件」里的一个分区 |",
    "| `chat.message.action` | AI 消息旁的动作按钮（keyed） |",
    "",
    "## 包写太大怎么办（很常见，别硬塞）",
    "",
    "一次 `plugin_define` 的参数是**一整段 JSON**，写太长会被模型输出上限截断 —— 那时你会收到",
    "`INVALID_ARGUMENTS` 且提示「参数 JSON 不完整（被输出上限截断）」。**不是你写错了 JSON**，是这一次装不下。两个办法：",
    "",
    "1. **分两版写**：第一版只定义必需字段、把界面做简单；`plugin_run` 跑通后，再 `plugin_define` 一个**新版本**（自动 +1）补上更多细节。",
    "2. **代码要短**：精简样式与重复结构，别把大段文字塞进代码里（说明文字放 `purpose`）。",
    "",
    "## 纪律与常见错误",
    "",
    "- **能力声明最小集**：多声明一个能力就多要一次用户授权；少声明会在调用时同步失败（错误里会说清缺哪个）。",
    "- **context 里没装载全书时 `chapters()` 是空的**：写界面别依赖它，用 `progress()`。",
    "- **不要在 render 里做重活**：它每次重渲染都会跑一遍。",
    "- **`ctx.log(...)` 不是白写的**：它进「设置 → 插件日志」面板，也进 `plugin_inspect(query=logs)` 与 `plugin_diagnose` 的 `logs`。",
    "  排查自己的插件时**先看日志** —— 它自己说了什么往往比猜快得多（记得声明 `log.write`）。",
    "- 写了界面但什么都没显示：先看 `plugin_inspect` 里那个槽位的 `wired` 是不是 false，再看 `plugin_diagnose` 的 `renderFailures` 与 `logs`。",
    "- 启动失败先看 `diagnose` 里的源码：`apply` 抛错、语法错误、引用不存在的 ctx 方法都会让它 FAILED。",
    "- 一切都做完以后，用一句话告诉用户：插件叫什么、显示在哪、怎么关掉（右侧「插件」面板）。",
    "- **做不了的先说清楚**：宿主还没有 文件（`fs.*`）与 调用模型（`llm.chat`）这两个门面，",
    "  沙箱里也**没有定时器**（不能「每隔一分钟自动刷新」）。用户要「定时提醒」这类需求时，直接说做不了，不要绕。",
    "  能做的：读当前书（目录/正文/检索/批注/进度/**阅读活动统计**）、改阅读位置、写批注、插件自己的存储、挂界面、覆盖主题颜色、",
    "  **访问已授权的域名**（`net.fetch`：查 API 余额、读网页/接口、抓 RSS 都行）。",
    "- **你写的插件默认只活在这次运行里**（重启就没了）。用户想留住它，要到「设置 → 插件」里点",
    "  「保留到插件目录」——这一步**必须由用户做**（写用户的文件系统是那一层的事），你只能提醒他，不能替他按。",
  ].join("\n"),
};
